### ISSUE TITLE
Input line does not show text typed in

### ISSUE THREAD

**Issue by arthef** [shannah/RADChatRoom#3]
I am still pretty early in the tutorial at adding send button.

The input line seems te not updated when I type text in there. I mean, I type a few letters 'abc' and nothing shows in the input line. Then I mouse-click on the any place inside the app and the input line shows the text I typed in. The same when I remove the text, etc...
So, the input seems like not being updated in letters typed.

Is there something I need to do in order to have the input show text typed right away?

**Comment by shannah** [comment]
I think there may some things in the CSS compiler and runtime that the projects depend on that haven't been released yet.  They will be updated on Friday.  You'll then be able to update your project libs to get the latest.  That should fix the issues you're having.

(That will be "Update project libs"; not to be confused with "Update cn1libs")

**Comment by arthef** [comment]
Thank you for letting me know.
But, how do I "Update project libs"?

**Comment by shannah** [comment]
![image](https://user-images.githubusercontent.com/2677562/79395020-9fd4ca00-7f2d-11ea-8ba6-cc5d5277bbb1.png)
...
![image](https://user-images.githubusercontent.com/2677562/79395075-b549f400-7f2d-11ea-9883-be1f3c188981.png)
...
![image](https://user-images.githubusercontent.com/2677562/79395086-bf6bf280-7f2d-11ea-90ea-729004b823e3.png)

**Comment by arthef** [comment]
Ah, ok, thank you. I will run this update on Friday then.

**Comment by arthef** [comment]
This seems to be not fixed yet. Typed in text does is not displayed in the input field until I click somewhere outside the inputline

**Comment by shannah** [comment]
I've added a sample in the CodenameOne Samples project that is a minimal chat room view with input.  It seems to work fine for me.  

You can run this sample in the SampleRunner.
https://www.codenameone.com/blog/sheets-samples.html

The sample name is RADChatRoomTest3

The source is [here](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/RADChatRoomTest3/RADChatRoomTest3.java)

**Comment by arthef** [comment]
The same exact problem happens on your demo app. I have tested it more and it looks like it works correctly on iOS app and on Android app. I mean, each letter is displayed right away when it is typed in.
However, in the simulator letters are not displayed right away. I could ignore this if it only happened in simulator. However, the problem also happens on Mac desktop app which is a significant issue then.

So, in other works I can quickly type many letters and usually on 1 letter shows. Then when I click with mouse anywhere inside the app (in simulator or on desktop app) the entire text shows in the input field.

**Comment by arthef** [comment]
Please let me know if I can provide you with any more information to investigate. I could also record a video to show you the problem if that helps.

**Comment by shannah** [comment]
Video would help.  Also if you can run the sample and confirm that it works for you.  If it works then try to modify it to reproduce the error

**Comment by shannah** [comment]
I can’t reproduce it in simulator.  What JDK are you on?  What os?

Can you post your desktop build for me to try it out?

**Comment by arthef** [comment]
Hi,
I can give you a link to desktop build but I would prefer not to post it publicly. Is there a way I can send it over to you privately?

On my development machine I use IntelliJ and OpenJDK 11.

**Comment by shannah** [comment]
Which OS do you use?

> I can give you a link to desktop build but I would prefer not to post it publicly. 

Can you upload to something like google drive and share it with me (steve@weblite.ca)?

**Comment by arthef** [comment]
Thank you. I have sent you an email with the link. I am on MacOS 10.15.4

**Comment by shannah** [comment]
I might need you to do a video of the problem.  Your app works fine for me (other than the ugly iOS6 theme). 
Tried on 10.15.4 and 10.12.6.  
JDK on desktop build should be irrelevant since the JRE is bundled.

**Comment by shannah** [comment]
Were you using the simulator on all those machines or the desktop build that you sent me?  I've now tried it (the app you sent) on 6 different machines of varying OS versions and hardware) and it works fine in every case.  I can't reproduce anything like what you've shown in the video.

**Comment by arthef** [comment]
Desktop build I sent to you was installed and tested on all the machines.

**Comment by shannah** [comment]
Perhaps if you write out a list of specific steps you are performing to reproduce the problem.  I'm out of ideas.  Unless I can reproduce the issue, I can't fix it.  And we've already removed all differences, it seems.

**Comment by arthef** [comment]
There is really nothing special I do. I just copy the dmg file onto relatively empty and unused mac, open the dmg file, copy the app to Applications and then run it from there.
Then, I starty typing in the input line. Letters in the input line do not show, as you could see on the video. After I press enter the entire text goes into the chat message.

Is the Mac desktop app really a native application or it is Java app with bundled JVM?

**Comment by shannah** [comment]
It’s a bundled jvm.

**Comment by arthef** [comment]
Ok, thank you. That explains it a bit. It seems this is some kind of Java problem on my Macs. I will try to investigate it. As I can replicate it under simulator, it makes it easier to track it down. Will keep you posted if I find anything.

**Comment by shannah** [comment]
The only thing I can think is the extensions folder.  

https://aldoblog.com/2002/05/where-to-put-java-extensions-on-mac-os-x/

These are no longer used in jdk9+ but the desktop build used jdk8 so it’s possible that some extension is conflicting.

**Comment by arthef** [comment]
Thank you. However, I think this is not related. I test the app on one of the Macs with no Java installed at all. The only Java on this mac is the one bundled into the app. I understand that nothing more should be needed.

I will try to track the event calls and and see what exactly happens when the call is received with each new character types in.

**Comment by arthef** [comment]
I was able to solve the problem by adding following line:
``` kotlin
if (CN.isDesktop() || CN.isSimulator()) entryField.repaint()
```
After line: https://github.com/shannah/RADChatRoom/blob/c09395ba7f5ac8ce6054b056b1dc3ca021c87a70/src/com/codename1/rad/ui/chatroom/ChatRoomView.java#L190
Probably this is not ideal solution but seems to be good enough for now.

**Comment by shannah** [comment]
Thanks.  I've applied the fix.
